language: node_js
node_js:
  - "10"
dist: trusty # needs Ubuntu Trusty
sudo: required  # no need for virtualization.
addons:
  chrome: stable # have Travis install chrome stable.
cache:
  directories:
    - node_modules

script:
  - npm test:unit
  - npm run lint
